server:
  port: 8084

spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 4
          max-idle: 4
          min-idle: 1

cart:
  ttl-seconds: ${CART_TTL_SECONDS:604800}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    hostname: cart-service
    prefer-ip-address: false
    non-secure-port: 8084
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: WARN
    com.ecommerce.cartservice: INFO